### ISSUE TITLE
Add information on build2

### ISSUE THREAD

**Issue by boris-kolpackov** [royjacobson/modules-report#1]
I see `build2` is not mentioned in this report. If you are interested in the state of modules in `build2`, this blog post provides the coverage:  https://build2.org/blog/build2-cxx20-modules-gcc.xhtml

**Comment by royjacobson** [comment]
Thanks! Do you think this is an accurate description of the current state of support?

> Build2 supports building modules with GCC since the start of 2021. [This](https://build2.org/blog/build2-cxx20-modules-gcc.xhtml) blog post has details on how to use it, and there is a [repository](https://github.com/build2/cxx20-modules-examples) with various usage examples.

**Comment by boris-kolpackov** [comment]
Yes, looks good to me, thanks!
