### ISSUE TITLE
Some new information about cmake, xmake and async_simple

### ISSUE THREAD

**Issue by ChuanqiXu9** [royjacobson/modules-report#2]
Currently async_simple contains the experimental support for modules  with xmake and cmake in main branch (https://github.com/alibaba/async_simple#c20-modules-support). While the support in main branch is actually a named modules' wrapper, [the modules branch](https://github.com/alibaba/async_simple/tree/CXX20Modules) contains lots of uses for named modules and it is compilable by cmake and xmake now.

**Comment by royjacobson** [comment]
Thanks! Updated with a link to the docs.
